version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Atantares\TemporalBundle\Runtime\TemporalRuntime

rpc:
  listen: tcp://0.0.0.0:6001

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 1

logs:
  level: debug
  channels:
    temporal.level: error
